[display]
fullscreen=true
high-dpi=true
multi-sampling=true

[gource]
author-time=true
auto-skip-seconds=2
colour-images=true
default-user-image=/home/teladi/Downloads/cat_svgs_session1/06_round_orange_cat_icon.svg
max-files=0
seconds-per-day=60

